on: [push, pull_request]
name: Dumpsys Parser Test

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Spotless check
        run: ./gradlew spotlessCheck

      - run: ./gradlew test